added github\workflows as well as index and styles.css files
MPDADDY/portfolio pull request #1
Opened 2023-04-29 09:32 UTC by MPDADDY

This is to test for linter errors.

2023-04-29 18:10 UTC, taldr27 reviewed
Hi @MPDADDY  

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

Thank you for submitting your project. Unfortunately, I have noticed that the linter tests are not passing. 

_HINT: I would suggest trying to remove the "hint-report" folder as it may be causing your `webhint` test to fail. This should allow your project to pass the necessary tests. Keep up the good work!_

----
Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready. 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

If you need any further help or have any questions, feel free to reach out to me on Slack as _**Diego Garcia**_.🎯

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit. <img align="right" src="https://media.giphy.com/media/kReKcfrs1YoTmt2AQt/giphy.gif" alt="gif"  width="3%"/>_

2023-04-30 17:49 UTC, MPDADDY commented
Thank you.


On Sat, Apr 29, 2023 at 9:10 PM Diego Garcia ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
>
> Hi @MPDADDY <https://github.com/MPDADDY>
>
> While you made a great effort in this project, unfortunately, I cannot
> proceed to review your code.
> Invalid Code Review Request
>
> Thank you for submitting your project. Unfortunately, I have noticed that
> the linter tests are not passing.
>
> *HINT: I would suggest trying to remove the "hint-report" folder as it may
> be causing your webhint test to fail. This should allow your project to
> pass the necessary tests. Keep up the good work!*
> ------------------------------
>
> Your Code Review Request will be marked as invalid in your Dashboard, so
> please submit a new one once you are ready. 🙏
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification.
>
> If you need any further help or have any questions, feel free to reach out
> to me on Slack as *Diego Garcia*.🎯
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> *Invalid Code Review Request does not count into the code reviews limit.
> [image: gif]
> <https://camo.githubusercontent.com/bb2ceca983f3ddaa1f0bccaff82b20fef67c881c39ad28f77ee04934bd14e9d0/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f6b52654b6366727331596f546d74324151742f67697068792e676966>*
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/MPDADDY/portfolio/pull/1#pullrequestreview-1407011831>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AX3FD7IBXKE3HQC4VTB3EZLXDVKRTANCNFSM6AAAAAAXQDMLAQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-05-01 08:52 UTC, wayungi reviewed
Hi @MPDADDY , 
![image](https://user-images.githubusercontent.com/99656687/224543512-ddbefa59-dc68-47c2-b7fe-f55acdacd3eb.png)

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request ❌ ❌ 

- [ ] You have submitted a project with a PR description that does not describe the introduced changes in detail

![DESC](https://user-images.githubusercontent.com/99656687/235431361-a349677a-9011-4d22-b334-6d814a6e4d34.png)


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-05-01 13:44 UTC, christianbiring1 reviewed
Hi @MPDADDY , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

# Invalid Code Review Request :heavy_multiplication_x: 
![Invalid](https://user-images.githubusercontent.com/97100091/235460264-cee26d70-c96a-4e3a-9824-366ed2413f8d.gif)

You have submitted a project, that is not set up professionally. kindly make sure:
- [ ] The title of your PR is descriptive,
Hint: YOu may consider saying: `Portfolio: setup and mobile first` instead of `added github\workflows as well as index and styles.css files`
- [ ] Kindly make sure your PR has a descriptive summary telling what changes have been introduced. like what have you worked on? i mean what did you do?

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-05-01 16:04 UTC, levy002 requested changes
## Hello @MPDADDY   , :wave:
### I'm Levy, your PR reviewer

Good job so far :+1: 
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif)

## Highlights
- No linter error :heavy_check_mark: 

## Status: REQUIRED CHANGES ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @levy002 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-01 16:04 UTC, levy002 commented on index.html
> +            </article>
- [ ] Kindly make sure to wrap the main title of your portfolio into the `h1` tag. [Check this link](https://www.reliablesoft.net/h1-tag/) for more info.

2023-05-01 16:04 UTC, levy002 commented on index.html
> +        </div>
- [ ] Kindly make sure to wrap the navigation links into the `nav` tag. The `nav` tag is for semantics reasons and the right position for convention and user experience for mobile devices.

2023-05-01 16:04 UTC, levy002 commented on styles.css
> +
- [ ] Kindly make sure to use the same typography on the main title of your portfolio in order to match the provided Figma design.

   - ### YOUR DESIGN
   
     ![image](https://user-images.githubusercontent.com/87197412/235480477-7e5846b0-45a5-4e45-b14e-c01f71663c67.png)

   - ### FIGMA DESIGN
   
   ![image](https://user-images.githubusercontent.com/87197412/235480524-82cccdb1-9430-4df1-8600-7251ae63e2c7.png)

2023-05-01 16:04 UTC, levy002 commented on styles.css
> +}
- [ ] Kindly make sure to remove the background image you added to the whole body because, in the Figma design, the body doesn't have a background image.  Please check very well you will notice that the background image is only added on the headline introduction section, which you gave the `.intro` class in your codebase. Kindly add this background image there and make sure it fits the width of the visible screen. 
    You will notice that your navbar now it has a background image but in the provided Figma design it doesn't have one, it's only the white color as the background. Kindly fix that.


    - ### YOUR DESIGN
    
    ![image](https://user-images.githubusercontent.com/87197412/235482525-c5ec2021-b25d-48e9-bd29-0858db75de47.png)

    - ### FIGMA DESIGN
    
    ![image](https://user-images.githubusercontent.com/87197412/235482570-969254d8-2116-4918-9d06-47062c892b0f.png)

2023-05-01 16:04 UTC, levy002 commented on styles.css
> +}
- [ ] Kindly make sure to align the headline intro contents by using CSS `flexbox` which gives us a lot of options to align all our elements, plus, it's responsive. Please make sure to provide enough space between the contents in order to match the provided Figma design.

  - ### YOUR DESIGN
  
     ![image](https://user-images.githubusercontent.com/87197412/235483756-640438d1-903d-4d32-aa44-1944fefb2344.png)

  - ### FIGMA DESIGN
  
    ![image](https://user-images.githubusercontent.com/87197412/235483839-61d7cabc-11d7-452d-98a4-c615cdcb2230.png)

2023-05-01 16:33 UTC, MPDADDY commented
Thank you so much for your proficiency in reviewing code.

On Mon, May 1, 2023 at 7:04 PM levy_ukwishaka ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
> Hello @MPDADDY <https://github.com/MPDADDY> , 👋 I'm Levy, your PR
> reviewer
>
> Good job so far 👍
> There are some issues that you still need to work on to go to the next
> project but you are almost there!
>
>
> <https://camo.githubusercontent.com/77566116408d88259ddadf7605a02b67a4e825e002a39682ca5f2e8bca8c4d64/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f4a713832345239334a734c775a436169534c2f67697068792e676966>
> Highlights
>
>    - No linter error ✔️
>
> Status: REQUIRED CHANGES ♻️
>
> *Check the comments under the review.*
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix is not crucial enough to stop
> the approval of this PR. However, I strongly recommend you to take them
> into account as they can make your code better.*
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me @levy002 <https://github.com/levy002> in your
> question so I can receive the notification.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
> ------------------------------
>
> In index.html
> <https://github.com/MPDADDY/portfolio/pull/1#discussion_r1181657392>:
>
> > +            <article>
> +                <h2>I'm Anold. Glad to see you</h2>
> +            </article>
>
>
>    - Kindly make sure to wrap the main title of your portfolio into the h1
>    tag. Check this link <https://www.reliablesoft.net/h1-tag/> for more
>    info.
>
> ------------------------------
>
> In index.html
> <https://github.com/MPDADDY/portfolio/pull/1#discussion_r1181658800>:
>
> > +        <div class="logo">
> +            <a href="index.html">My Logo</a>
> +        </div>
> +        <div class="humberger">
> +            <i class="fa fa-bars"></i>
> +        </div>
>
>
>    - Kindly make sure to wrap the navigation links into the nav tag. The
>    nav tag is for semantics reasons and the right position for convention
>    and user experience for mobile devices.
>
> ------------------------------
>
> In styles.css
> <https://github.com/MPDADDY/portfolio/pull/1#discussion_r1181667656>:
>
> > +section article h2 {
> +  font-size: 40px;
> +  font-family: 'Poppins', sans-serif;
> +  font-style: normal;
> +  font-weight: 700;
> +  line-height: 52px;
> +}
> +
>
>
>    -
>
>    Kindly make sure to use the same typography on the main title of your
>    portfolio in order to match the provided Figma design.
>    - YOUR DESIGN
>
>       [image: image]
>       <https://user-images.githubusercontent.com/87197412/235480477-7e5846b0-45a5-4e45-b14e-c01f71663c67.png>
>       - FIGMA DESIGN
>
>    [image: image]
>    <https://user-images.githubusercontent.com/87197412/235480524-82cccdb1-9430-4df1-8600-7251ae63e2c7.png>
>
> ------------------------------
>
> In styles.css
> <https://github.com/MPDADDY/portfolio/pull/1#discussion_r1181677347>:
>
> > +body {
> +  background-image: url(./images/header-shapes\ mobile.png);
> +  background-repeat: no-repeat;
> +  background-position: 100%;
> +  background-size: contain;
> +}
>
>
>    -
>
>    Kindly make sure to remove the background image you added to the whole
>    body because, in the Figma design, the body doesn't have a background
>    image. Please check very well you will notice that the background image is
>    only added on the headline introduction section, which you gave the
>    .intro class in your codebase. Kindly add this background image there
>    and make sure it fits the width of the visible screen.
>    You will notice that your navbar now it has a background image but in
>    the provided Figma design it doesn't have one, it's only the white color as
>    the background. Kindly fix that.
>    - YOUR DESIGN
>
>    [image: image]
>    <https://user-images.githubusercontent.com/87197412/235482525-c5ec2021-b25d-48e9-bd29-0858db75de47.png>
>    - FIGMA DESIGN
>
>    [image: image]
>    <https://user-images.githubusercontent.com/87197412/235482570-969254d8-2116-4918-9d06-47062c892b0f.png>
>
> ------------------------------
>
> In styles.css
> <https://github.com/MPDADDY/portfolio/pull/1#discussion_r1181682584>:
>
> > +section {
> +  padding: 2rem;
> +  max-width: 378px;
> +}
>
>
>    -
>
>    Kindly make sure to align the headline intro contents by using CSS
>    flexbox which gives us a lot of options to align all our elements,
>    plus, it's responsive. Please make sure to provide enough space between the
>    contents in order to match the provided Figma design.
>    - YOUR DESIGN
>
>       [image: image]
>       <https://user-images.githubusercontent.com/87197412/235483756-640438d1-903d-4d32-aa44-1944fefb2344.png>
>       - FIGMA DESIGN
>
>       [image: image]
>       <https://user-images.githubusercontent.com/87197412/235483839-61d7cabc-11d7-452d-98a4-c615cdcb2230.png>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/MPDADDY/portfolio/pull/1#pullrequestreview-1407727640>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AX3FD7KCAFSTCMOKZLMMVXTXD7NI5ANCNFSM6AAAAAAXQDMLAQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-05-01 23:05 UTC, Alfredbis29 requested changes
#  STATUS: REQUIRED CHANGES 
 ## Hi @MPDADDY 
 Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

 ![](https://camo.githubusercontent.com/dbe642c07a12e38cdc021eb826931557cc1eb657023c3609cc10e8f3b47f06d7/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f6c344a7a686a56435169576765414f46612f67697068792e676966) 
 ## Highlights 
 :heavy_check_mark: Linters are passing.
:heavy_check_mark: You have a good code structure.
:heavy_check_mark: Linters are green
 
 ## Required Changes 
- [ ] Check under the review

 ## Optional suggestions 

Check under the review 

 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._
 
 Cheers and Happy coding! :clap: :clap: :clap:
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @Alfredbis29 in your question so I can receive the notification.
 
 **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
 
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-01 23:05 UTC, Alfredbis29 commented on styles.css
> +nav {
- [ OPTIONAL] kindly update the header to not overlay the background image in order to follow good design practices and ensure consistency with the Figma design

Your design:
<img width="252" alt="image" src="https://user-images.githubusercontent.com/88894525/235544772-84969db3-d770-4493-b55c-aeed1c31d2ef.png">

Figma Design:
<img width="238" alt="image" src="https://user-images.githubusercontent.com/88894525/235544916-923eaee9-1968-4137-9fe0-90891ef87b3a.png">

2023-05-01 23:05 UTC, Alfredbis29 commented on index.html
> +      <nav>
- [ ] Kindly as the previous CR mentioned, wrap only the navigations links into the `nav` tag not the whole header, in your case the `div` with `humberger` class should be the one to wrap in the `nav` tag for semantics reason.

2023-05-02 14:42 UTC, emmiiorji approved these changes
Hi @MPDADDY, 

# Status: Approved ✅

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<div align='center'>
<img src='https://user-images.githubusercontent.com/20554583/220871050-9893fe6a-46a0-42a3-8a44-46ac0f7f1154.gif'/>
</div>

## Good Highlights

- Requested changes have been implemented

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-02 14:48 UTC, MPDADDY commented
Thank you so much.

On Tue, May 2, 2023 at 5:42 PM Emmanuel Orji-Ihuoma <
***@***.***> wrote:

> ***@***.**** approved this pull request.
>
> Hi @MPDADDY <https://github.com/MPDADDY>,
> Status: Approved ✅
>
> Your project is complete! There is nothing else to say other than... it's
> time to merge it [image: :shipit:]
> Congratulations! 🎉
>
> <https://user-images.githubusercontent.com/20554583/220871050-9893fe6a-46a0-42a3-8a44-46ac0f7f1154.gif>
> Good Highlights
>
>    - Requested changes have been implemented
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification.
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/MPDADDY/portfolio/pull/1#pullrequestreview-1409265706>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AX3FD7LVV2XSGBTWKOJXWZTXEEMOHANCNFSM6AAAAAAXQDMLAQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-05-02 14:50 UTC, merged

2023-05-02 14:52 UTC, MPDADDY commented
This project is complete for set up and mobile-first version of it.