Portfolio:  contact form section
MPDADDY/portfolio pull request #3
Opened 2023-05-09 17:58 UTC by MPDADDY

- [ ] Added a contact form in the footer section.
- [ ] Added a submit button.

2023-05-09 23:31 UTC, Olamarx requested changes
Hi @MPDADDY, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not have the get started section setup properly, kindly describe to the user how to localize your project.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-05-10 14:28 UTC, Shisui6 reviewed
Hi @MPDADDY, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request 🛠️

You have submitted a project, with an unprofessional readme file. Please make sure to go through your readme file and fill out all sections with information for your project. Please also make sure to remove the section descriptions (lines that start with >) as they are just comments which are not supposed to be in the final version 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!🍻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid, unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-05-10 19:36 UTC, Abenezer-Tilahun requested changes
Hi @MPDADDY  @denigit5  , 

Great job for implemented  the some of the Project Requirement , but there are some changes that need to be implemented in order to proceed to the next project 👍

## Highlights 👏🏻
✔️ No Linter errors
✔️ Correct Git Hub-Flow
✔️ Good commit messages
✔️ Professional README

![almost](https://user-images.githubusercontent.com/65860678/170491251-b1add8ba-b18f-4648-a893-20e510d957fd.gif)

## Required Changes ♻️
_Check the comments below the review._


_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-10 19:36 UTC, Abenezer-Tilahun commented on index.html
> +              <form action="https://formspree.io/f/{form_id}" method="post">
- [ ] Kindly makes sure that the form are  submitted successfully with valid input values. When I try to submit the form with values I got the following error related with the `{form_id}`, So to fix the issues Kindly use your own `{form_id}` by creating in the [formspree service](https://formspree.io/html).
![Capture](https://github.com/MPDADDY/portfolio/assets/93598189/0ccf4ac5-95a9-4976-a202-488b326da274)

2023-05-10 19:36 UTC, Abenezer-Tilahun commented on index.html
> +                     <textarea name="comments" id="comments" cols="30" rows="10" placeholder="write your message here..." required></textarea>
- [ ] Kindly make sure that Message input has `maxlength="500"` attribute. So Kindly Fix it.

2023-05-11 08:02 UTC, LionRouge1 approved these changes
Hi @MPDADDY & @denigit5,

# STATUS: APPROVED! 🥇 💯 
Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:

![done](https://media.giphy.com/media/a5llhdWKMOIfneMCpB/giphy.gif)

Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

2023-05-11 08:39 UTC, MPDADDY commented
The mobile version of the portfolio project is comlete.

2023-05-11 08:41 UTC, MPDADDY commented
I want to thank all reviewers for great reviews youv'e given to this project.

2023-05-11 08:42 UTC, merged