Portfolio desktop version
MPDADDY/portfolio pull request #4
Opened 2023-05-12 12:46 UTC by MPDADDY

- [ ] Added media query to make the desktop version look good.
- [ ] Downloaded desktop images and added them to the desktop version of the project.

2023-05-12 13:40 UTC, divinecharlotte requested changes
Hi @MPDADDY      , 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

## To Highlight 💯 

- linters are passing 👍 
- Descriptive Pr 👍 




 
![](https://media.giphy.com/media/tKyrc0NTlEcGWdThp4/giphy.gif)
## Required Changes ♻️

- [ ] kindly consider customizing the authors section in your readme to make it contain only you as you are the one who participated in this branch and this will make it more professional

- [ ] kindly consider customizing your license section by removing the NOTE there to make your readme professional as that was given only to guide you not to be added I your readme 

_Check the comments under the review._
## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-12 13:40 UTC, divinecharlotte commented on index.html
>      <section class="intro">
- [ ] kindly consider making sure that the background image for this section covers the whole section as given in the Figma design  to make it an exact duplicate of the given design check the images below  for more clarification 
- your design 👇 
<img width="1381" alt="Screen Shot 2023-05-12 at 15 11 19" src="https://github.com/MPDADDY/portfolio/assets/60146030/0883208b-a3f1-45d4-84ae-d8523a43e3f3">


- Figma design 👇 
<img width="813" alt="Screen Shot 2023-05-12 at 15 13 40" src="https://github.com/MPDADDY/portfolio/assets/60146030/f33104e1-2aa5-41c6-a4b4-47b3ae6df58b">

2023-05-12 13:40 UTC, divinecharlotte commented on index.html
>                                  <img width="8px" height="8px" src="images/Ellipse 12.png" alt="">
- [ ] kindly consider giving your icons some border-radius and the right background color  to make them look exactly like the one provided in the design you may also download them from Figma to make it quick  and doing so will demonstrate your skills in implementing the provided design exactly check the images below to easily see the difference 
- [ ] kindly consider also giving the `see project` button the same color as the one given in Figma to make it an exact duplicate of the given one 
- your design 👇 
<img width="735" alt="Screen Shot 2023-05-12 at 15 25 10" src="https://github.com/MPDADDY/portfolio/assets/60146030/d5b8ce3b-bda0-409d-9abc-01cda8dbbc7d">


- Figma design 👇 
<img width="802" alt="Screen Shot 2023-05-12 at 15 25 38" src="https://github.com/MPDADDY/portfolio/assets/60146030/80bebb8d-6556-46be-81a8-5f51b7488440">

2023-05-12 13:40 UTC, divinecharlotte commented on index.html
> +            <article id="what_i_do" class="padding">
- [ ] kindly consider giving this section the same margin and padding ,width and fort the `get my resume` button give it the same color as the one in Figma to implement exactly the one in the design consider checking on the below screenshots to understand what you have to update clearer
- your design 👇
<img width="770" alt="Screen Shot 2023-05-12 at 15 31 51" src="https://github.com/MPDADDY/portfolio/assets/60146030/d4417ef1-c487-4a31-8bfd-4aa060c48910">

- Figma design 👇 
<img width="808" alt="Screen Shot 2023-05-12 at 15 32 59" src="https://github.com/MPDADDY/portfolio/assets/60146030/5aacbe5b-a1fa-4871-8ed6-bfb5c4212aba">

2023-05-12 18:22 UTC, NahnahAJ requested changes
## Project Status: CHANGES REQUIRED :recycle: 
Hi @MPDADDY , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which haven't been addressed yet.
<img src="https://media0.giphy.com/media/VlqzeaRnhCvPLfrSh6/giphy.gif"/>

 ## Highlights
- Most of the requested changes implemented ✔️ 
- No linter errors ✔️ 
- Good use of GitHub flow ✔️ 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @NahnahAJ in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-12 18:22 UTC, nahnahdev commented on index.html
>      <section class="intro">
- [ ] Good job so far @MPDADDY However, just as the previous reviewer mentioned, kindly consider making sure that the `background image` for this section covers the whole section as given in the Figma design to make it an exact duplicate of the Figma design as specified in the Project Requirements. 😉 
- Your Design
<img width="1269" alt="Screen Shot 2023-05-12 at 5 52 47 PM" src="https://github.com/MPDADDY/portfolio/assets/102699958/88fdedf4-2b55-4687-a5f8-94227b2d6505">

- The Figma Design
<img width="719" alt="Screen Shot 2023-05-12 at 5 47 27 PM" src="https://github.com/MPDADDY/portfolio/assets/102699958/f6c2e225-253d-40bf-a5c6-5137d31702e5">

2023-05-12 18:22 UTC, NahnahAJ commented on index.html
>                                  <img width="8px" height="8px" src="images/Ellipse 12.png" alt="">
- Just as the previous reviewer mentioned, kindly consider changing the background color of the icons between the list items so it looks similar to that of the Figma design 👍 
- Your Design
<img width="327" alt="Screen Shot 2023-05-12 at 5 59 39 PM" src="https://github.com/MPDADDY/portfolio/assets/102699958/70da0dda-15bb-4383-929e-fdd8064fcd68">

- The Figma Design
<img width="359" alt="Screen Shot 2023-05-12 at 5 59 56 PM" src="https://github.com/MPDADDY/portfolio/assets/102699958/4a3432d8-d837-47c0-a3a1-94cc8b0d628d">

2023-05-12 18:22 UTC, NahnahAJ commented on index.html
> +                    me.
- [ ] Lastly, your `About section` looks great but in order to implement the `About me` content taking up lesser space than the `languages, skills and frameworks` as the previous reviewer suggested, I will suggest you style the main container of the section with` display: grid` and ensure that the `about me` part is wrapped in a separate container and takes 40% of the page and the `languages, skills and frameworks` also wrapped in a separate container and takes 60% of the page.
- This way your design looks more similar to the Figma design 😉 
- Your Design
<img width="1273" alt="Screen Shot 2023-05-12 at 6 20 34 PM" src="https://github.com/MPDADDY/portfolio/assets/102699958/cc521eb8-f970-40c3-afc7-0d5b9fcb63ad">

- The Figma Design

<img width="719" alt="Screen Shot 2023-05-12 at 6 20 22 PM" src="https://github.com/MPDADDY/portfolio/assets/102699958/e446f1d5-f3ef-446b-9616-da120496bd05">

2023-05-13 00:08 UTC, Shedrack-Sunday approved these changes
Hi @MPDADDY 

Congratulations! 🎉 Your project is complete and ready to be merged! 🚀

![image](https://i.pinimg.com/originals/3d/d2/07/3dd207237b39dcacd832f94a35428255.gif)


## Highlights
- Good use CSS selectors✔️  
- Moderate UI ✅


## Optional Suggestions 💡
While these comments with the [OPTIONAL] prefix won't prevent the approval of this pull request, I strongly recommend taking them into account as they can improve your code. Some of them were missed by the previous reviewer and addressing them will really enhance your application.
Cheers, and Happy coding!👏👏👏

If you have any questions or need clarification on anything, feel free to leave a comment in the pull request thread, and don't forget to tag me so I'll receive the notification.

As per the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project. If you feel that the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-05-13 05:32 UTC, MPDADDY commented
This desktop version is now good-looking.

2023-05-13 05:32 UTC, merged